# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build /Template/CleanArchitecture.WebApi.sln $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: 'CleanArchitecture.WebApi.csproj'
    custom: 'dotnet pack'