version: '3.8'

services:
  project_name.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=4443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssW0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx  
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.ASPNET/HTTPS:ro
      - ~/.aspnet/https:/https:ro